/**
 * Shared conversation title generation service.
 *
 * Provides a single reusable primitive for generating and persisting
 * conversation titles across all creation paths.
 *
 * Two invariants hold everywhere titles are written:
 *
 * 1. **Set once.** A conversation's title is decided by the first pass that
 *    produces a real one and then never changes on its own. Only placeholders
 *    ("Untitled", "Generating title…") remain open, so a failed first pass can
 *    be repaired. User renames are never touched.
 * 2. **Quality floor.** A generated title that is filler, a conversational
 *    acknowledgement, or a fragment is discarded, not persisted — the
 *    deterministic title is always the better of the two.
 */

import { getConfiguredProvider } from "../providers/provider-send-message.js";
import type { Provider } from "../providers/types.js";
import { runBtwSidechain } from "../runtime/btw-sidechain.js";
import { publishConversationTitleChanged } from "../runtime/sync/resource-sync-events.js";
import { getLogger } from "../util/logger.js";
import { Mutex } from "../util/mutex.js";
import {
  getConversation,
  getMessages,
  type MessageRow,
  updateConversationTitle,
} from "./conversation-crud.js";

const log = getLogger("conversation-title-service");

// ── Types ────────────────────────────────────────────────────────────

export type TitleOrigin =
  | "runtime_api"
  | "channel_inbound"
  | "voice_outbound"
  | "voice_inbound"
  | "guardian_request"
  | "schedule"
  | "task"
  | "watcher"
  | "subagent"
  | "sequence"
  | "heartbeat"
  | "filing"
  | "local"
  | "task_submit"
  | "memory_consolidation"
  | "memory_retrospective"
  | "misc";

export interface TitleContext {
  origin: TitleOrigin;
  conversationKey?: string;
  sourceChannel?: string;
  assistantId?: string;
  externalChatId?: string;
  displayName?: string;
  username?: string;
  triggerTextSnippet?: string;
  systemHint?: string;
  metadataHints?: string[];
  uxBrief?: string;
}

// ── Placeholder / loading state ──────────────────────────────────────

export const GENERATING_TITLE = "Generating title...";
const UNTITLED_FALLBACK = "Untitled Conversation";

// ── `conversations.isAutoTitle` values ───────────────────────────────
//
// Most readers treat the column as a boolean ("not user-set"); the two
// distinct non-zero values let the title pipeline tell HOW a title was set.

/** Title was set by the user (a manual rename). Never auto-overwritten. */
export const AUTO_TITLE_USER_SET = 0;
/** Title was generated by an LLM from conversation content. */
export const AUTO_TITLE_LLM = 1;
/**
 * Title was derived deterministically from bootstrap context — no LLM call,
 * no user input. These name the work they were created for ("Task: …",
 * "Schedule: …", "Kit asset: …"), so they are as final as an LLM title; only
 * the placeholder shapes below stay replaceable.
 */
export const AUTO_TITLE_DETERMINISTIC = 2;

// ── Replaceability check ─────────────────────────────────────────────

const REPLACEABLE_PATTERNS = [
  /^Runtime:\s/,
  /^New Conversation$/,
  /^Untitled$/,
  /^Untitled Conversation$/,
  /^Generating title\.\.\.$/,
  // Seeded on every live-voice thread before there is a transcript to title
  // from (`live-voice/live-voice-thread.ts`). It names the medium, not the
  // conversation, so the end-of-call pass is expected to replace it.
  /^Voice conversation$/,
];

/**
 * Check whether a title is a system-generated placeholder that can be
 * safely overwritten by auto-generated titles. Returns `false` for
 * user-provided custom titles.
 */
export function isReplaceableTitle(title: string | null): boolean {
  if (title == null || title.trim() === "") return true;
  return REPLACEABLE_PATTERNS.some((pattern) => pattern.test(title));
}

/**
 * Whether auto-generation may overwrite the conversation's current title.
 *
 * Titles are **set once**: the first pass that produces a real title owns it
 * for the life of the conversation, matching every other chat product. Only a
 * placeholder — the empty/"Untitled"/"Generating title…" shapes above — is
 * still open for a title, so a conversation whose first pass failed can be
 * repaired later.
 *
 * Deterministic bootstrap titles are deliberately **not** replaceable. They
 * are derived from a `systemHint` that already names the work ("Task: Book the
 * flights", "Kit asset: one_pager"), so swapping them for an LLM title later
 * changes a label the user has already read and learned, which is exactly the
 * churn this policy exists to stop. The boilerplate deterministic case —
 * bootstrap context with nothing to say, which falls back to "Untitled
 * Conversation" — is covered by `REPLACEABLE_PATTERNS`, so it still upgrades.
 *
 * A user-set title (`AUTO_TITLE_USER_SET`) is never replaced, even if the user
 * chose to name their conversation something placeholder-shaped.
 */
function canReplaceTitle(conversation: {
  title: string | null;
  isAutoTitle: number;
}): boolean {
  if (conversation.isAutoTitle === AUTO_TITLE_USER_SET) return false;
  return isReplaceableTitle(conversation.title);
}

/**
 * Derive a deterministic title from bootstrap context without an LLM call.
 * Used for background/system conversations (heartbeat runs, scheduled jobs,
 * subagents, retrospectives) where an LLM-generated title is not worth the
 * tokens — the bootstrap `systemHint` already names the work. Persist it with
 * `AUTO_TITLE_DETERMINISTIC`; it is the conversation's final title unless the
 * context was empty enough to fall back to the "Untitled Conversation"
 * placeholder, which a later pass may still fill in.
 */
export function deriveDeterministicTitle(context: TitleContext): string {
  const base = deriveFallbackTitle(context) ?? UNTITLED_FALLBACK;
  return truncateTitle(base.replace(/\s+/g, " ").trim());
}

// ── Title generation ─────────────────────────────────────────────────

export interface GenerateTitleParams {
  conversationId: string;
  /** Provider to use for LLM call. Falls back to getConfiguredProvider(). */
  provider?: Provider;
  /** Context about how/where the conversation was created. */
  context?: TitleContext;
  /** User message text (first turn). */
  userMessage?: string;
  /** Assistant response text (first turn). */
  assistantResponse?: string;
  /** Abort signal. */
  signal?: AbortSignal;
}

/**
 * Generate a conversation title via LLM and persist it, but only if the
 * current title is still a placeholder (set-once policy — see
 * `canReplaceTitle`). A generation that comes back as filler or a fragment is
 * discarded rather than persisted (see `normalizeTitle`).
 */
export async function generateAndPersistConversationTitle(
  params: GenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  const { conversationId, context, userMessage, assistantResponse, signal } =
    params;

  // Check current title is replaceable
  const conversation = getConversation(conversationId);
  if (conversation && !canReplaceTitle(conversation)) {
    return { title: conversation.title!, updated: false };
  }

  const provider =
    params.provider ?? (await getConfiguredProvider("conversationTitle"));
  if (!provider) {
    // No provider available — fall back to context-derived title or untitled.
    // When the context named the work, that name stands; when it did not, the
    // "Untitled Conversation" placeholder keeps a later pass free to fill it in.
    const fallback = deriveFallbackTitle(context) ?? UNTITLED_FALLBACK;
    updateConversationTitle(conversationId, fallback, AUTO_TITLE_DETERMINISTIC);
    publishConversationTitleChanged(conversationId, fallback);
    return { title: fallback, updated: true };
  }

  const prompt = buildTitlePrompt(context, userMessage, assistantResponse);
  const result = await runBtwSidechain({
    content: prompt,
    provider,
    systemPrompt: buildTitleSystemPrompt(),
    tools: [],
    callSite: "conversationTitle",
    signal,
    timeoutMs: 15_000,
  });
  const title = normalizeTitle(result.text);
  if (title) {
    // Re-check replaceability before persisting (race guard)
    const current = getConversation(conversationId);
    if (current && !canReplaceTitle(current)) {
      return { title: current.title!, updated: false };
    }

    updateConversationTitle(conversationId, title, AUTO_TITLE_LLM);
    publishConversationTitleChanged(conversationId, title);
    log.info({ conversationId, title }, "Auto-generated conversation title");
    return { title, updated: true };
  }

  // No text in response — use fallback
  // Re-check replaceability before persisting (race guard — same as the
  // text-response path above). A concurrent custom rename may have landed
  // while the LLM request was in-flight; writing unconditionally would
  // clobber the user's intent.
  const currentForFallback = getConversation(conversationId);
  if (currentForFallback && !canReplaceTitle(currentForFallback)) {
    return { title: currentForFallback.title!, updated: false };
  }

  const fallback = deriveFallbackTitle(context) ?? UNTITLED_FALLBACK;
  updateConversationTitle(conversationId, fallback, AUTO_TITLE_DETERMINISTIC);
  publishConversationTitleChanged(conversationId, fallback);
  return { title: fallback, updated: true };
}

// ── Serial title-generation queue ────────────────────────────────────

/**
 * Each title generation makes an LLM call. Without serialization, burst
 * conversation creation (e.g. 5 new chats in quick succession) fires N
 * concurrent requests that can hit provider rate limits or contend for
 * API capacity, causing later calls to time out and fall back to
 * "Untitled Conversation".
 *
 * A serial queue ensures at most one title-generation LLM call is
 * in-flight at a time. Each call is lightweight (~1–3 s for a ≤5-word
 * title), so the added serial latency is modest and invisible to the
 * user (the UI shows "Generating title…" as a placeholder during the
 * wait). Both initial generation and second-pass regeneration share
 * this queue since they hit the same provider.
 */
export const titleMutex = new Mutex();

/**
 * Fire-and-forget wrapper for title generation. Failures are logged
 * but do not propagate. On failure, replaces loading placeholder with
 * a stable fallback title so loading state is never permanent.
 *
 * Calls are serialized via {@link titleMutex} so burst conversation
 * creation does not overwhelm the LLM provider.
 */
export function queueGenerateConversationTitle(
  params: GenerateTitleParams,
): void {
  void titleMutex
    .withLock(async () => {
      await generateAndPersistConversationTitle(params);
    })
    .catch((err) => {
      log.warn(
        { err, conversationId: params.conversationId },
        "Failed to generate conversation title (non-fatal)",
      );
      // Replace loading placeholder with stable fallback
      try {
        const conversation = getConversation(params.conversationId);
        if (conversation && conversation.title === GENERATING_TITLE) {
          const fallback =
            deriveFallbackTitle(params.context) ?? UNTITLED_FALLBACK;
          updateConversationTitle(params.conversationId, fallback);
          publishConversationTitleChanged(params.conversationId, fallback);
        }
      } catch {
        // Best-effort
      }
    });
}

// ── Title regeneration (second pass) ─────────────────────────────────

export interface RegenerateTitleParams {
  conversationId: string;
  provider?: Provider;
  signal?: AbortSignal;
}

/**
 * Re-generate a conversation title using the last 3 stored messages.
 *
 * This is a **repair** pass, not a re-titling pass: it only runs while the
 * conversation is still on a placeholder (see `canReplaceTitle`), i.e. when
 * the first pass produced nothing usable. A conversation that already has a
 * real title keeps it — a title that mutates under the user mid-conversation
 * is worse than a slightly imprecise one that stays put.
 */
export async function regenerateConversationTitle(
  params: RegenerateTitleParams,
): Promise<{ title: string; updated: boolean }> {
  const { conversationId, signal } = params;

  const conversation = getConversation(conversationId);
  if (!conversation || !canReplaceTitle(conversation)) {
    return { title: conversation?.title ?? UNTITLED_FALLBACK, updated: false };
  }

  const provider =
    params.provider ?? (await getConfiguredProvider("conversationTitle"));
  if (!provider) {
    return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
  }

  const allMessages = getMessages(conversationId);
  const recentMessages = allMessages.slice(-3);
  if (recentMessages.length === 0) {
    return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
  }

  const prompt = buildRegenerationPrompt(recentMessages);
  // Skip the LLM call if no messages yielded extractable text — the prompt
  // would be just the "Recent messages:" header, and the model tends to
  // fabricate a meta-title about the emptiness rather than decline.
  if (!/\n(?:User|Assistant): /.test(prompt)) {
    return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
  }
  const result = await runBtwSidechain({
    content: prompt,
    provider,
    systemPrompt: buildTitleSystemPrompt(),
    tools: [],
    callSite: "conversationTitle",
    signal,
    timeoutMs: 15_000,
  });
  const title = normalizeTitle(result.text);
  if (title) {
    // Re-check replaceability before persisting (race guard: a manual rename
    // or a competing generation pass may have landed while the LLM request
    // was in flight).
    const current = getConversation(conversationId);
    if (!current || !canReplaceTitle(current)) {
      return { title: current?.title ?? UNTITLED_FALLBACK, updated: false };
    }

    updateConversationTitle(conversationId, title, AUTO_TITLE_LLM);
    publishConversationTitleChanged(conversationId, title);
    log.info(
      { conversationId, title },
      "Re-generated conversation title (second pass)",
    );
    return { title, updated: true };
  }

  return { title: conversation.title ?? UNTITLED_FALLBACK, updated: false };
}

/**
 * Fire-and-forget wrapper for title regeneration.
 *
 * Serialized via the same {@link titleMutex} as initial generation.
 */
export function queueRegenerateConversationTitle(
  params: RegenerateTitleParams,
): void {
  void titleMutex
    .withLock(async () => {
      await regenerateConversationTitle(params);
    })
    .catch((err) => {
      log.warn(
        { err, conversationId: params.conversationId },
        "Failed to regenerate conversation title (non-fatal)",
      );
    });
}

// ── Internal helpers ─────────────────────────────────────────────────

/**
 * Dedicated system prompt for title generation. Replaces the default
 * assistant system prompt that btw-sidechain would otherwise inject,
 * which caused the model to respond to the conversation content instead
 * of titling it.
 */
function buildTitleSystemPrompt(): string {
  return [
    "You generate ultra-concise conversation titles. Output ONLY the title text — no explanation, no quotes, no markdown, no preamble.",
    "",
    "Rules:",
    "- 2–5 words maximum. Titles longer than 5 words are unacceptable — ruthlessly compress to a short noun phrase",
    "- 40 characters absolute maximum — if your title exceeds 40 characters it will be truncated and look broken",
    "- Summarize only the TOPIC, not the request or instructions",
    "- Noun phrases are ideal (e.g. 'Auth Middleware Rewrite', 'Docker Volume Mounts', 'Onboarding Flow')",
    "- Think: what would make a scannable sidebar label?",
    "- Do NOT echo back what the user asked you to do",
    "- Do NOT respond to the conversation content",
    "- Do NOT assess feasibility or comment on capabilities",
    "- If input is sparse or references external context, extract a topic from the words that ARE present (e.g. 'so about that t-shirt...' → 'T-Shirt Discussion'). Never describe the absence, emptiness, or insufficiency of context — titles like 'Missing Context', 'Unclear Request', 'No Topic' are forbidden",
  ].join("\n");
}

function buildTitlePrompt(
  context?: TitleContext,
  userMessage?: string,
  assistantResponse?: string,
): string {
  const parts: string[] = [];

  if (context) {
    const hints: string[] = [];
    if (context.sourceChannel) hints.push(`Channel: ${context.sourceChannel}`);
    if (context.displayName) hints.push(`User: ${context.displayName}`);
    if (context.systemHint) hints.push(`Context: ${context.systemHint}`);
    if (context.uxBrief) hints.push(`Brief: ${context.uxBrief}`);
    if (context.metadataHints?.length)
      hints.push(`Hints: ${context.metadataHints.join(", ")}`);
    if (hints.length > 0) {
      parts.push("Metadata:", ...hints, "");
    }
  }

  if (userMessage) {
    parts.push(`User: ${stripThinkingTags(userMessage)}`);
  }
  if (assistantResponse) {
    parts.push(`Assistant: ${stripThinkingTags(assistantResponse)}`);
  }

  return parts.join("\n");
}

const META_FAILURE_TITLES = new Set([
  "missing context",
  "no context",
  "insufficient context",
  "unclear context",
  "empty context",
  "no topic",
  "unclear topic",
  "unclear request",
  "unclear message",
  "empty conversation",
  "empty message",
  "no content",
]);

/**
 * Conversational filler the model sometimes answers with instead of titling —
 * acknowledgements, one-word replies, and self-referential non-titles. A
 * conversation labelled "Sure" or "Got it" in the sidebar tells the user
 * nothing about what is inside it, so these are rejected outright and the
 * caller keeps the placeholder/deterministic title instead.
 */
const FILLER_TITLES = new Set([
  "sure",
  "sure thing",
  "ok",
  "okay",
  "k",
  "alright",
  "all right",
  "got it",
  "gotcha",
  "understood",
  "acknowledged",
  "noted",
  "certainly",
  "of course",
  "no problem",
  "here you go",
  "here it is",
  "here's the title",
  "here is the title",
  "sounds good",
  "yes",
  "yep",
  "yeah",
  "no",
  "nope",
  "done",
  "hello",
  "hi",
  "hey",
  "thanks",
  "thank you",
  "title",
  "conversation",
  "conversation title",
  "chat",
  "untitled",
  "summary",
  "response",
  "reply",
  "n/a",
  "none",
]);

/**
 * Preambles the model prepends when it answers conversationally instead of
 * emitting a bare title ("Sure, here's the title: Kickoff Plan"). Only a
 * lead-in closed by punctuation is stripped — requiring the separator is what
 * keeps a real title whose first word happens to be one of these ("OK Reply",
 * "Sure Thing Bakery") intact.
 */
const LEAD_IN_PATTERNS = [
  /^(?:sure|okay|ok|alright|certainly|of course|got it|no problem|understood|here you go|here it is)\s*[:,\-—–!.]+\s*/i,
  /^(?:here(?:'s| is)\s+(?:a|the|your)?\s*title|the title is)\s*[:,\-—–]+\s*/i,
  /^title\s*[:,\-—–]+\s*/i,
];

const MAX_TITLE_LENGTH = 40;
const MAX_TITLE_WORDS = 7;
/**
 * Shortest single-word title we accept. Real one-word titles are typically a
 * noun or an all-caps acronym; anything shorter reads as a fragment — which is
 * precisely what a clipped or half-emitted completion leaves behind.
 */
const MIN_SINGLE_WORD_TITLE_LENGTH = 4;

function truncateTitle(title: string): string {
  if (title.length <= MAX_TITLE_LENGTH) return title;
  const words = title.split(/\s+/);
  if (words.length <= MAX_TITLE_WORDS) {
    // Long words but few of them — truncate to char limit at word boundary
    let result = "";
    for (const word of words) {
      const candidate = result ? result + " " + word : word;
      if (candidate.length > MAX_TITLE_LENGTH) break;
      result = candidate;
    }
    // A word-boundary cut that keeps only the first word discards nearly the
    // whole title: one long token (a URL, a hyphenated slug) is enough to blow
    // the budget and leave a bare fragment behind — "Sur https://…/landing" is
    // stored as "Sur". Prefer a hard character cut, which at least carries the
    // start of the second word.
    if (words.length > 1 && !result.includes(" ")) {
      return title.slice(0, MAX_TITLE_LENGTH).trim();
    }
    return result || title.slice(0, MAX_TITLE_LENGTH);
  }
  // Too many words — trim to 5 words
  return words.slice(0, 5).join(" ");
}

/** Lowercased title with surrounding punctuation removed, for set lookups. */
function titleKey(title: string): string {
  return title
    .toLowerCase()
    .replace(/^[\s"'`*_.,:;!?—–-]+|[\s"'`*_.,:;!?—–-]+$/g, "")
    .replace(/\s+/g, " ");
}

/**
 * Quality floor for a generated title. A rejected title is never persisted —
 * the caller falls back to the deterministic title, which is always at least
 * as informative as the junk being rejected.
 *
 * Length alone is a poor test ("Q3 budget", "Gmail auth fix", "PONG" are all
 * legitimate), so this rejects on shape instead: known filler, meta-failure
 * commentary, and single-word fragments too short to be a word — with all-caps
 * acronyms ("SEO", "API") exempted from the length rule.
 */
function isLowQualityTitle(title: string): boolean {
  const key = titleKey(title);
  if (key === "") return true;
  if (META_FAILURE_TITLES.has(key)) return true;
  if (FILLER_TITLES.has(key)) return true;
  if (!key.includes(" ")) {
    const bare = title.replace(/[^\p{L}\p{N}]/gu, "");
    const isAcronym = bare.length >= 2 && bare === bare.toUpperCase();
    if (!isAcronym && bare.length < MIN_SINGLE_WORD_TITLE_LENGTH) return true;
  }
  return false;
}

/**
 * Turn a raw model completion into a storable title, or "" when the completion
 * is not usable as one. Returning "" (rather than a best-effort string) is what
 * keeps a bad generation from overwriting a good title.
 */
function normalizeTitle(raw: string): string {
  let title = raw.trim().replace(/^["']|["']$/g, "");
  title = stripMarkdown(title);
  title = stripThinkingTags(title);
  // Collapse newlines: a multi-line completion must not become a multi-line
  // sidebar label.
  title = title.replace(/\s+/g, " ").trim();
  title = stripLeadIns(title);
  title = truncateTitle(title).trim();
  if (isLowQualityTitle(title)) {
    // Log what was rejected. Title side-chain calls are not written to
    // `llm_request_logs`, so without this the model's actual output is
    // unrecoverable — which is exactly why the completion behind the
    // reported "Sur" title could never be identified. The caller falls back
    // to the deterministic title; this is the only record that it happened.
    log.warn(
      { raw: raw.slice(0, 120), normalized: title },
      "rejected a low-quality generated title (keeping the existing one)",
    );
    return "";
  }
  return title;
}

/**
 * Peel conversational preambles off the front of a completion. Bounded
 * iteration handles the stacked case ("Sure — here's the title: Kickoff").
 */
function stripLeadIns(title: string): string {
  let result = title;
  for (let pass = 0; pass < LEAD_IN_PATTERNS.length; pass++) {
    const before = result;
    for (const pattern of LEAD_IN_PATTERNS) {
      const stripped = result.replace(pattern, "").trim();
      // Never strip the whole title away — "Sure" alone is filler, and
      // `isLowQualityTitle` is the one that should reject it.
      if (stripped !== "") result = stripped;
    }
    if (result === before) break;
  }
  return result;
}

/** Strip thinking tags so they don't bleed into generated titles. */
function stripThinkingTags(text: string): string {
  return text
    .replace(/<thinking>[\s\S]*?<\/thinking>/gi, "")
    .replace(/<thought>[\s\S]*?<\/thought>/gi, "")
    .replace(/<think>[\s\S]*?<\/think>/gi, "")
    .replace(/<thought>/gi, "")
    .replace(/<\/thought>/gi, "")
    .replace(/<thinking>/gi, "")
    .replace(/<\/thinking>/gi, "")
    .replace(/<think>/gi, "")
    .replace(/<\/think>/gi, "")
    .replace(/<:[^>]*>/gi, "");
}

/** Strip common markdown formatting so titles render as plain text. */
function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "$1") // **bold**
    .replace(/__(.+?)__/g, "$1") // __bold__
    .replace(/\*(.+?)\*/g, "$1") // *italic*
    .replace(/(?<!\w)_(.+?)_(?!\w)/g, "$1") // _italic_ (word-boundary-aware to preserve snake_case)
    .replace(/~~(.+?)~~/g, "$1") // ~~strikethrough~~
    .replace(/`(.+?)`/g, "$1") // `code`
    .replace(/\[(.+?)\]\(.+?\)/g, "$1") // [link](url)
    .replace(/^#{1,6}\s+/gm, ""); // # headings
}

function deriveFallbackTitle(context?: TitleContext): string | null {
  if (!context) return null;
  if (context.systemHint) return context.systemHint;
  if (context.uxBrief) return context.uxBrief;
  return null;
}

/**
 * Extract only human-authored text from stored message content for title
 * generation. Unlike extractTextFromStoredMessageContent (which includes
 * tool metadata like "Tool use (...): {...}"), this only extracts:
 * - `text` blocks (the actual conversation content)
 * - `tool_result` string content (topical signal from tool responses)
 *   — web_search_tool_result is skipped (structured search data, not topical)
 *
 * Returns empty string for content-block arrays with no extractable text,
 * preventing raw JSON from polluting the title prompt.
 */
function extractTextForTitle(raw: string): string {
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "string") return parsed;
    if (!Array.isArray(parsed)) return raw;
    const texts: string[] = [];
    for (const block of parsed) {
      if (!block || typeof block !== "object") continue;
      if (block.type === "text" && typeof block.text === "string") {
        texts.push(block.text);
        // guard:allow-tool-result-only — web_search_tool_result has structured
        // search result arrays, not useful for title generation; only plain
        // tool_result string content carries topical signal.
      } else if (block.type === "tool_result") {
        if (typeof block.content === "string") {
          texts.push(block.content);
        } else if (Array.isArray(block.content)) {
          for (const nested of block.content) {
            if (
              nested &&
              typeof nested === "object" &&
              nested.type === "text" &&
              typeof nested.text === "string"
            ) {
              texts.push(nested.text);
            }
          }
        }
      }
    }
    return texts.join("\n");
  } catch {
    return raw;
  }
}

function buildRegenerationPrompt(recentMessages: MessageRow[]): string {
  const parts: string[] = ["Recent messages:"];

  for (const msg of recentMessages) {
    const text = extractTextForTitle(msg.content);
    if (!text) continue;
    const role = msg.role === "user" ? "User" : "Assistant";
    parts.push(`${role}: ${stripThinkingTags(text)}`);
  }

  return parts.join("\n");
}
